config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  # root "articles#index"

  root 'lists#index'
  resources :lists, only: [ :create, :new, :show] do
    member do
      resources :bookmarks, only: [:new, :create]
    end
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :list_id, :movie_id, presence: true
  validates :comment, length: { minimum: 6 }
  validates :list_id, uniqueness: { scope: :movie_id }
end

app/models/list.rb
class List < ApplicationRecord

  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_one_attached :photo

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: :destroy
  before_action :set_list, only: [:new, :create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list_id = @list.id
    @bookmark.save!
    redirect_to list_path(@list)
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show destroy]

  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.create(list_params)
    redirect_to list_path(@list)
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Add a movie to your <%= @list.name %> list</h3>
        <%= simple_form_for [@list, @bookmark] do |f| %>
          <%= f.input :comment, placeholder: 'Enter a comment about the movie' %>
          <%= f.association :movie,  prompt: 'Select a movie' %>
          <%= f.submit class: 'btn btn-succes' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% [@list, @bookmark]  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.12"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar'%>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="cover" style="background-image: url(https://img.freepik.com/free-photo/arrangement-cinema-elements-bicolor-background-with-copy-space_23-2148457840.jpg?w=1380&t=st=1666181181~exp=1666181781~hmac=74390de2fc7dec25f309e935a3659847da4978433099d91baa87bd577a53341a);">
  <div class="container-cover">
    <h1>Keep all your movies!</h1>
    <h2 class="typed-js" data-controller="typed-js">Movie Time!</h2>
  </div>
</div>

<div class="container">
  <div class="cards d-flex align-items-center justify-content-between mb-3">
    <h3>My Lists</h3>
    <%= link_to "Create a movie list", new_list_path, class: "btn btn-success" %>
  </div>
</div>

<div class="wrapper">
    <% @lists.each do |list| %>
    <%= link_to list_path(list) do %>
    <% if list.photo.attached?  %>
      <div class="card-list m-3" style="background-image: url('<%=  (cl_image_path list.photo.key, height: 300, crop: :fill )%>')">
       </div>
        <%= list.name %>
        <% else %>
        <%= list.name %>
        <% end %>
      <%end %>
  <% end %>
</div>

<br/>
<hr/>

<div class="card-trip">
  <%= cl_image_tag("sample", width: 60, height: 60, crop: :fill) %>
  <div class="card-trip-infos">
    <div>
      <h2>Title</h2>
      <p>Read more!</p>
    </div>
  </div>
</div>


<div class="starWars"></div>

<%= cl_image_tag("sample", width: 400, height: 300, crop: :fill) %>

<%# not apply %>
<%# <%= image_tag("/app/assets/images/rails_watch_list.jpg", {:style => "width:100px;"}) %>

app/views/lists/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-6">
      <div class="bg-white rounded">
        <h3>Create a new list 🎞</h3>
        <%= simple_form_for @list do |f| %>
          <%= f.input :name, placeholder: 'Comedy, Drama, Doku' %>
          <%= f.input :photo, as: :file %>
          <%= f.submit class: 'btn btn-success' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="position-relative">
  <div class="card-category">
    <h1><%= @list.name %></h1>
  </div>
  <span class="movie-tag"><%= pluralize(@list.movies.size, "movie") %></span>
</div>
<div class="container mb-5">
  <div class="d-flex justify-content-between">
    <span class="mb-2 d-block"><p><em class="text-muted"><%= "You can save now your movies" if @list.movies.empty? %></em></p></span>
    <div>
      <button type="button" class="btn btn-flat" data-bs-toggle="modal" data-bs-target="#new_movie_modal">
        Add your movie
      </button>
      <%= link_to "Delete your list", list_path(@list), class: "btn btn-danger", data: { turbo_method: :delete, turbo_confirm: "Ready to delete your list?" } %>
    </div>
  </div>
  <div class="row">
    <% @list.movies.each do |movie| %>
      <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
      <div class="col-12">
        <div class="bg-white rounded">
          <%= image_tag movie.poster_url, alt: movie.title, class: "movie-img" %>
          <div class="p-3 rounded-bottom d-flex flex-column">
            <strong><%= movie.title %> <span> <%= movie.rating %> <i class="fas fa-star star-yellow"></i></span></strong>
            <p class="text-muted"><%= movie.overview %></p>
            <div class="d-flex align-items-end justify-content-between pt-4">
              <div>
                <i class="fas fa-quote-left me-2"></i><p class="flex-grow-1"><%= bookmark.comment %></p>
              </div>
              <p class="text-right flex"><%= link_to "delete", bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Ready to remove #{movie.title} from your #{@list.name} list"} %></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon px-3">
  <%= link_to root_path do %>
    <%= image_tag "https://img.freepik.com/free-vector/happy-emoji_53876-25513.jpg?w=740&t=st=1666180704~exp=1666181304~hmac=8e12249048f0f8bcb58a70cb3502cc1e38a9ce861b91280d1e4e66d95ee2bcb5", alt: "logo", class: "logo" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto">
      <li class="nav-item active">
        <%= link_to "My lists", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "New list", new_list_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</div>